Misoten-B/airship-frontend

src/app/cards/[card_id]/page.tsx, src/app/cards/create/page.tsx, src/app/cards/page.tsx, src/app/page.tsx, src/app/register/page.tsx
=> add: ルーティング大枠

.github/README.md
=> add: readme

.github/README.md, package-lock.json, package.json, src/lib/recoil/atom.ts, src/shared/components/forms/Form/Form.tsx, src/shared/components/forms/Form/FormItem.tsx, src/shared/components/forms/Form/index.ts, src/shared/components/forms/Input/Input.tsx, src/shared/components/forms/Input/index.ts, src/shared/components/guards/Guard.tsx, src/shared/components/guards/index.ts, src/shared/hooks/useForm.ts
- close #00
`react-hook-form`と`zod`によるバリデーションを行うためのライブラリを追加しました。
リクエストで使用するスキーマを`./src/shared/schemas`内でまとめたいので`antd`の`rules`を使わない実装になります。
=> add: react-hook-form zod

src/shared/components/common/Divider/Divider.tsx, src/shared/components/common/Input/PasswordInput/PasswordInput.tsx, src/shared/components/common/Input/TextInput/TextInput.tsx, src/shared/components/common/Layout/Card.tsx, src/shared/components/common/Layout/Center.tsx, src/shared/components/common/Layout/Paper.tsx
- close #00
- commonのcard, center, paper, divider追加
=> feat: common layouts

package-lock.json, package.json, src/shared/components/common/ModelViewer.tsx
=> add: model-viewer

.github/workflows/build.yaml
=> fix: build workflow

.github/workflows/build.yaml, src/app/page.tsx, src/shared/components/common/QRCode/QRCode.tsx, src/shared/components/common/QRCode/index.ts
- close #23
汎用的に使える画像入りQRコードコンポーネントを作成しました。
使用例として、indexに表示させています。
現状QRコード内画像が正方形でないと縦横比が崩れてしまいます。
qrcode.reactライブラリで、QR内画像スタイル変更が簡単にできなさそうだったので、一旦保留にします。
=> feat: 画像入りQRコードコンポーネント作成

.github/workflows/main_airship.yml
=> fix: deploy workflow

src/app/ar_assets/[ar_asset_id]/page.tsx, src/app/ar_assets/create/_components/CreateArAssetStepper.tsx, src/app/ar_assets/create/_components/StepContent/CompletedArAsset.tsx, src/app/ar_assets/create/_components/StepContent/Select3dModel.tsx, src/app/ar_assets/create/_components/StepContent/SpeakingSettings.tsx, src/app/ar_assets/create/_components/StepContent/UploadQRCodeInsideImage.tsx, src/app/ar_assets/create/_components/StepContent/index.ts, src/app/ar_assets/create/page.tsx, src/app/ar_assets/page.tsx, src/shared/components/common/Stepper/Stepper.tsx, src/shared/components/common/Stepper/index.ts
- close #51 
mantineのstepperをimportし、QRコード作成のstepperを作成しました。
stepperの中身のコンテンツについては枠だけ作成しました。
`http://localhost:3000/ar_assets/create`で確認できます。
=> QRコード作成のStepper作成

aspida.config.js
=> hotfix: swagger.yaml

.github/workflows/main_airship.yml
=> chore: include .env when building

src/app/ar_assets/_components/ArAssetCard.tsx, src/app/ar_assets/_components/ArAssetList.tsx, src/app/ar_assets/page.tsx, src/shared/components/common/Layout/SimpleGrid.tsx, src/shared/components/common/Layout/index.ts, src/shared/components/icons/IconPencil.tsx, src/shared/components/icons/IconSpeakerphone.tsx, src/shared/components/icons/index.ts
- close #68 
responsive対応
frontend/assets/85974240/c76f9e37-9c33-408b-b8a6-af3ec03d9fbd">
button修正
=> QRコード一覧 UI

src/app/login/_components/Login.tsx, src/app/login/_components/RegisterCard/Form/MailInput.tsx, src/app/login/_components/RegisterCard/Form/PasswordInput.tsx, src/app/login/_components/RegisterCard/Form/index.ts, src/app/login/_components/RegisterCard/LoginCard.tsx, src/app/login/_components/RegisterCard/index.ts, src/app/login/page.tsx, src/app/register/_components/Register.tsx
=> Feat login

src/shared/hooks/auth/AuthContext.tsx
=> fix: getIdToken()を使用するように変更

src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/Display3dModel.tsx, src/app/ar-assets/create/_components/CreateArAssetStepper.tsx, src/app/ar-assets/create/_components/StepContent/Select3dModel.tsx, src/shared/components/features/SelectThreeDModel.tsx, src/shared/hooks/restapi/v1/ThreeDimentionalModel/useGetThreeDimentionalModels.ts
- close #106 
ラジオボタンで選択する3Dモーダルをコンポーネントに切り出し、実際にバックエンドから取得する。
まだ共通部分を完全に切り出せていないため、別issueにて。
=> Feat select three dimentional model

next.config.js, package-lock.json, package.json, src/app/ar-assets/create/_components/StepContent/SpeakingSettingsContent/RecordedModelSettings.tsx, src/shared/hooks/useAudioRecorder.ts, src/shared/lib/ffmpeg/index.ts
- close #110 
ステップ1を頑張ってくれてるとのことなので、そちらが固まるまではステップ2内だけで音声データを管理しています。
#109 にあるようにデザイン面に課題が残っています。
=> Feat: 音声録音フックの導入

src/app/cards/[card_id]/_components/CardPage.tsx, src/app/cards/[card_id]/page.tsx, src/app/cards/_components/Cards.tsx
=> Feat: 名刺取得フック呼び出し

src/app/ar-assets/[ar_asset_id]/public/_components/ArAssets.tsx, src/app/ar-assets/[ar_asset_id]/public/page.tsx, src/shared/hooks/restapi/v1/ArAssets/index.ts, src/shared/hooks/restapi/v1/ArAssets/useGetPublicArAsset.ts
=> feat: ARアセット公開ページAPI疎通

src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetail.tsx, src/app/ar-assets/_components/ArAssetItem.tsx, src/app/ar-assets/create/_components/StepContent/CompletedArAsset/index.tsx, src/shared/components/common/QRCode/QRCode.stories.tsx, src/shared/components/common/QRCode/QRCode.tsx, src/shared/components/features/BusinessCard/BusinessCard.tsx
- close #125 
- close #26 
名刺の背景を反映
リファクタリング
=> Feat business card background

src/shared/components/common/ModelViewer.tsx, src/shared/components/features/BusinessCard/BusinessCard.stories.tsx, src/shared/components/features/BusinessCard/BusinessCard.tsx, src/shared/components/features/QRCode/helper.ts, src/shared/components/features/SelectThreeDModel.tsx, src/shared/hooks/restapi/v1/BusinessCard/useCreateBusinessCard.ts, src/shared/hooks/restapi/v1/BusinessCard/useUpdateBusinessCard.ts
=> Fix: バックエンドの更新に合わせて変更

package-lock.json, package.json, src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetail.tsx, src/app/ar-assets/create/_components/StepContent/CompletedArAsset/index.tsx, src/shared/components/common/QRCode/QRCode.tsx, src/shared/constants/index.ts, src/shared/hooks/useComponentToPng.ts
- close #133
対象コンポーネントに画像が含まれていて、その画像が壊れているとダウンロードできないようなのでQRコードをCCにしてエラーハンドリングを追加しました
=> Feat QRコード画像化

src/shared/constants/restapi.ts
=> fix: backend-status

src/shared/providers/index.tsx
- close #00
（cssってどこで読み込めば良いんだろう、、、）
=> fix: NotificationのCSS読み込み忘れ修正

src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/Display3dModel.tsx
=> fix: issue-129

src/shared/components/features/BusinessCard/BusinessCard.tsx
- close #00
参照が循環してたので修正しときました
=> fix: 循環参照の解消

src/shared/components/features/LoginButton.tsx, src/shared/providers/index.tsx, src/shared/providers/loading.tsx
- close #00
グローバルなローディングの実装（呼び出してはいません）
動作確認済み
=> Feat global loading

src/app/ar-assets/_components/ArAssetItem.tsx, src/app/cards/create/_components/CreateCard.tsx, src/app/cards/create/_components/OpenSelectQRCodeButton.tsx, src/app/cards/create/_components/SelectQRModal.tsx
- close #126 
左上に一応Radioを置いているのですが、自分では選択の実装ができないので他の方にお願いしたいです。
スクロール機能はCardsが増えた時にできます。
=> add:mantine QRSelectModal作成

src/app/ar-assets/_components/ArAssetList.tsx, src/app/cards/create/_components/CreateCard.tsx, src/app/cards/create/_components/SelectQRCodeModal.tsx, src/app/cards/create/_components/SelectQRModal.tsx, src/shared/components/features/QRCode/ArAssetItem.tsx
- close #128 
ArAssetを実際に選択して保存できるように
=> feat: ArAssetを実際に選べるように

src/app/ar-assets/create/_components/StepContent/UploadQRCodeInsideImage/index.tsx, src/app/record/_components/RecordPage.tsx, src/shared/providers/loading.tsx
=> AI連携時にローディングを表示

package-lock.json, package.json, src/shared/components/features/BusinessCard/BusinessCardBackgroundCrop.tsx, src/shared/components/features/BusinessCard/BusinessCardDesignModal.tsx, src/shared/components/features/BusinessCard/ColorOnlyModal.tsx, src/shared/components/features/BusinessCard/getCroppedImg.ts, src/shared/hooks/restapi/v1/BusinessCardBackground/useCreateBusinessCardBackground.ts
=> Feat background image update

src/app/ar-assets/[ar_asset_id]/public/_components/ArAssets.tsx, src/app/ar-assets/[ar_asset_id]/public/_components/CircleProgress.tsx, src/shared/components/icons/index.ts
- close #00
AR画面の再生ボタンなどの見た目調整
=> feat: 見た目の調整

src/shared/components/features/QRCode/helper.ts
=> hotfix: 応急処置として環境変数にデフォルト値を設定

src/app/cards/_components/Cards.tsx
- close #00
ボタンクリックで名刺の作成画面へ飛ぶようにリンクを書き足しました。
=> Create card href

src/app/record/_components/RecordPage.tsx
=> fix: 音声モデル生成時画面遷移

src/app/cards/create/_components/CreateCard.tsx, src/shared/components/features/BusinessCard/BusinessCard.stories.tsx, src/shared/components/features/BusinessCard/BusinessCard.tsx
=> hotfix: 名刺コンポーネントのQRコードURL修正

src/app/(auth)/login/_components/RegisterCard/LoginCard.tsx, src/app/(auth)/register/_components/RegisterCard/RegisterCard.tsx, src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetail.tsx, src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/Display3dModel.tsx, src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/QRCodeInsideImage.tsx, src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/SpeakingArea.tsx, src/app/ar-assets/[ar_asset_id]/page.tsx, src/shared/components/common/QRCode/QRCode.tsx, src/shared/components/features/QRCode/ArAssetItem.tsx, src/shared/components/features/SigninGoogleButton.tsx
- close #00
見た目だけ、実際のデータが入るようにしました。
処理はバックエンドが終わっていないので後ほど
=> Feat arsasset detail 見た目だけ

src/app/record/_components/RecordPage.tsx, src/shared/components/icons/index.ts, src/shared/hooks/restapi/v1/BusinessCard/useUpdateBusinessCard.ts
=> feat: record modal

src/app/cards/[card_id]/public/_components/CardArAssets.tsx, src/app/cards/[card_id]/public/_components/CircleProgress.tsx, src/app/cards/[card_id]/public/page.tsx, src/shared/hooks/restapi/v1/BusinessCard/index.ts, src/shared/hooks/restapi/v1/BusinessCard/useGetPublicBusinessCard.ts
- close #00
バックエンド実装後、実際のデータをとってきて名刺を背景に表示。
見た目を整えていないので、できたら真ん中に表示
=> feat: arの背景に名刺を配置

package-lock.json, src/app/ar-assets/create/_components/StepContent/CompletedArAsset/index.tsx, src/app/ar-assets/create/_components/StepContent/Select3dModel/index.tsx, src/app/ar-assets/create/_components/StepContent/UploadQRCodeInsideImage/index.tsx, src/shared/components/common/Button/CopyButton.tsx, src/shared/components/common/Button/index.ts, src/shared/components/features/BusinessCard/BusinessCardBackgroundCrop.tsx, src/shared/components/features/SelectThreeDModel.tsx
- close #148 
見た目とかバリデーションとか調整
=> Change qrcode stepper display

src/app/cards/[card_id]/_components/CardPage.tsx, src/shared/constants/routes.ts
=> feat: cardpage

src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/DeleteButtonContainer/DeleteButtonContainer.tsx
=> feat: ARアセット削除確認モーダル

src/app/ar-assets/[ar_asset_id]/_components/ArAssetDetailContent/Display3dModel/Display3dModel.tsx, src/app/cards/[card_id]/_components/CardPage.tsx, src/app/cards/_components/Cards.tsx
=> fix: エラーとか見た目の調整

src/shared/components/layouts/GlobalNav/GlobalNav.tsx
=> fix: ヘッダーのiphone崩れ

src/app/_components/Overview/Overview.module.css, src/app/_components/QRCodeSample/QRCodeSample.module.css, src/app/_components/UsageSection/UsageSection.module.css
=> fix: cssモジュールの入れ子削除

src/app/cards/create/_components/CreateCard.tsx, src/shared/components/features/BusinessCard/BusinessCard.tsx, src/shared/components/features/QRCode/helper.ts, src/shared/components/features/QRCode/index.ts, src/shared/components/features/index.ts
=> hotfix: 名刺のQRコードを読み込んだ際の遷移先変更

src/app/cards/[card_id]/_components/CardPage.tsx
=> feat: 名刺削除実装

src/shared/providers/index.tsx
=> feat: 401 redirect

src/app/record/_components/RecordPage.tsx
=> feat: record sample
